#build Setting
markdown: kramdown
# url: "https://realdjclone.github.io"
# permalink: pretty
# your url


# the base hostname & protocol for your site
# baseurl: /barangay-obrero

exclude: ['README.md']

port: 8080

highlighter: rouge

sass:
    sass_dir: assets/css
    stytle: :nested
